services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "./build.sh && chmod +x build.sh && ./build.sh"
    startCommand: "./start.sh && chmod +x start.sh && ./start.sh"
    region: Singapore (Southeast Asia)
    envVars:
      - key: PASSWORD
        sync: false
      - key: EMAIL
        sync: false
      - key: API_KEY
        sync: false
      - key: E_PASS
        sync: false
      - key: E_NAME
        sync: false
